services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:latest
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=mysecretpassword
      - NODE_ENV=development
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
    ports:
      - "5679:5678"
    volumes:
      
      - C:/Users/jaque/meu-projeto-n8n/n8n-nodes-random:/home/node/.n8n/custom/n8n-nodes-random
    depends_on:
      - postgres

volumes:
  postgres_data: